[versions]
kotlin = "1.8.10"
androidx_core = "1.10.1"
androidx_appcompat = "1.7.0"
material = "1.11.0"
constraint_layout = "2.1.7"
junit = "4.13.2"
espresso = "3.5.1"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint_layout" }

# Test dependencies are included here under the same 'libraries' section
junit = { module = "junit:junit", version.ref = "junit" }
junitExt = { module = "androidx.test.ext:junit", version = "1.1.5" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
androidApplication = { id = "com.android.application", version = "8.9.0" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version = "1.8.10" }
